dist: bionic

services:
  - docker

language: c

env:
  - TARGET_DISTRIBUTION=centos8
  - TARGET_DISTRIBUTION=amazonlinux2

script:
  # extend the timeout to get the tests report.
  - travis_wait 30 make "$TARGET_DISTRIBUTION"

before_deploy:
  - make bintray

deploy:
  - provider: bintray
    user: shogo82148
    key: '$BINTRAY_API_KEY'
    file: ./bintray/bintray-redis.json
    skip_cleanup: true
  - provider: bintray
    user: shogo82148
    key: '$BINTRAY_API_KEY'
    file: ./bintray/bintray-redis-debuginfo.json
    skip_cleanup: true
  - provider: bintray
    user: shogo82148
    key: '$BINTRAY_API_KEY'
    file: ./bintray/bintray-redis-devel.json
    skip_cleanup: true
  - provider: bintray
    user: shogo82148
    key: '$BINTRAY_API_KEY'
    file: ./bintray/bintray-redis-doc.json
    skip_cleanup: true
  - provider: bintray
    user: shogo82148
    key: '$BINTRAY_API_KEY'
    file: ./bintray/bintray-redis-trib.json
    skip_cleanup: true
