FROM centos:6
ENV HOME /
RUN yum update -y
RUN yum install -y rpm-build redhat-rpm-config rpmdevtools gcc-c++ tar make tcl which
RUN rpmdev-setuptree
RUN echo '%_docdir   %{_datadir}/doc' >> /.rpmmacros
ADD ./rpmbuild/ /rpmbuild/
RUN chown -R root:root /rpmbuild
RUN rpmbuild -ba /rpmbuild/SPECS/redis.spec
RUN tar -czf /tmp/redis.tar.gz -C /rpmbuild RPMS SRPMS
CMD ["/bin/true"]
