FROM amazonlinux:2
ENV HOME /
RUN yum update -y
RUN yum install -y rpm-build redhat-rpm-config rpmdevtools gcc-c++ tar make tcl which procps libatomic-devel openssl-devel
RUN rpmdev-setuptree
ADD ./rpmbuild/ /rpmbuild/
RUN chown -R root:root /rpmbuild
RUN rpmbuild -ba /rpmbuild/SPECS/redis.spec
RUN tar -czf /tmp/redis.tar.gz -C /rpmbuild RPMS SRPMS
CMD ["/bin/true"]
