FROM rockylinux/rockylinux:8
ENV HOME /
RUN dnf update -y
RUN dnf install -y rpm-build redhat-rpm-config rpmdevtools gcc-c++ tar make tcl which procps openssl-devel
RUN rpmdev-setuptree
ADD ./rpmbuild/ /rpmbuild/
RUN chown -R root:root /rpmbuild
RUN rpmbuild -ba /rpmbuild/SPECS/redis.spec
RUN tar -czf /tmp/redis.tar.gz -C /rpmbuild RPMS SRPMS
CMD ["/bin/true"]
