name: build

on:
  pull_request:
  push:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - amazonlinux2
          - amazonlinux2022
          - centos7
          - almalinux8
          - almalinux9
          - rockylinux8
          - rockylinux9
        platform:
          - linux/amd64
          # - linux/arm64
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v4
      - name: build
        run: |
          make ${{ matrix.distribution }}
        env:
          PLATFORM: ${{ matrix.platform }}

      - name: Configure AWS Credentials
        uses: shogo82148/actions-aws-assume-role@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::445285296882:role/rpm-repository-users-RedisRole-1XPLYZ0MTT1E9
          role-session-tagging: true
      - name: upload
        run: |
          make upload
