name: reviewdog
on: [pull_request]

permissions:
  contents: read
  checks: write
  pull-requests: write
  issues: write

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1

  rpmlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: rpmlint
        uses: shogo82148/actions-rpmlint@v0
        with:
          rpmlint_flags: rpmbuild/SPECS/*.spec
